### ISSUE TITLE
Trigger card does not trigger

### ISSUE THREAD

**Issue by jeroenvano** [jordenc/image.grabber#1]
Hi it looks to me that the Trigger card does not trigger. [TRIGGER] Image was grabbed (contains the base64 encoded image data in a token, for use in compatible apps such as the Homey Telegram app)

The flow with the [ACTION] Grab image card works but after it does not trigger the Image was grabbed flow. If I look for the token under TAGS it does not list.

**Comment by jordenc** [comment]
I use it very often and experience no problems. Can you tell me what you are trying to grab? Perhaps show both the flows.

**Comment by jeroenvano** [comment]
Sorry Jorden, I found out that your app trigger does work. I am having
issues with http calls from a cam that does not work to trigger a movement
condition. The movement condition change triggers your app to grab an
image.

You can close this issue.

Regards, Jeroen


Op 6 jun. 2017 15:39 schreef "Jorden" <notifications@github.com>:

I use it very often and experience no problems. Can you tell me what you
are trying to grab? Perhaps show both the flows.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jordenc/image.grabber/issues/1#issuecomment-306488919>,
or mute the thread

**Comment by jordenc** [comment]
No problem, good to hear you found what caused it.
