### ISSUE TITLE
Takkng/sending the image is slow

### ISSUE THREAD

**Issue by 2benl** [jordenc/image.grabber#11]
Since imagegrabber supports Homeys own image tags processing an image takes much longer. 4mp > 1 min.

**Comment by jordenc** [comment]
This is caused by Homey, not by the app. The Homey developers are looking into it.

**Comment by 2benl** [comment]
Can I sideload an old version of imagegrabber and the telegram app with your own image tokens? I don’t see any fast progress if Athom is looking into this.

**Comment by jordenc** [comment]
You can, but some things will no longer work (for example, received messages on the Telegram bot might not come through to Homey)
