### ISSUE TITLE
Image Grabber werkt niet met Homey 2.0 RC

### ISSUE THREAD

**Issue by FrankRinkens** [jordenc/image.grabber#13]
Image Grabber werkt niet met Homey 2.0 RC. gemigreerde werkende flow van 1.5 werkt niet meer. kan geen nieuwe flow maken omdat flow tags niet werken

**Comment by jordenc** [comment]
Die flow tags is volgens mij een bekend probleem en ligt aan Homey, niet aan de app:

Compared to Homey v1.5, this update has a few limitations:
<cut>
— Flow Tags cannot be entered in text fields

**Comment by FrankRinkens** [comment]
Andere apps waar flows met tags in zitten die gemigreerd zijn van v1.5 werken wel. Image grabber is bij mij dood na de upgrade. Maar misschien dat het idd weer werkt als homey aangepast is. Ik denk ik meld iig even dat het nu een app is die niet meer werkt.

**Comment by jordenc** [comment]
Ik zal het eens testen, heb hier op kantoor een geupdatete Homey versie. Kom er zo op terug!

**Comment by jordenc** [comment]
Nieuwe flow aanmaken, URL van een jpg afbeelding er in geplakt:
![img_4459](https://user-images.githubusercontent.com/17727803/49939257-9ae8ac00-fedc-11e8-9339-9c466f450f61.PNG)

Tweede flow aanmaken, "als er een afbeelding is gegrabbed":
![img_4460](https://user-images.githubusercontent.com/17727803/49939273-a8059b00-fedc-11e8-853a-36ec48709bfc.PNG)

Dan sturen we 'm op Telegram:
![img_4461](https://user-images.githubusercontent.com/17727803/49939280-b05dd600-fedc-11e8-8f15-47e5887c15f2.PNG)

En op Telegram komt ie ook gewoon aan als ik de flow uitvoer:
![img_4462](https://user-images.githubusercontent.com/17727803/49939312-c2d80f80-fedc-11e8-923c-614872c8f9ca.PNG)

**Comment by FrankRinkens** [comment]
Ok, ziet er goed uit. en hoe heb je de tag Image erin gekregen als dit nu niet werkt binnen homey 2.0?

**Comment by jordenc** [comment]
Het blijkt alleen niet te werken in "tekst" velden, maar dat werkte sowieso al niet met image tags. Bij Telegram moet je de optie "Send an image" of "Stuur een afbeelding" kiezen.

**Comment by FrankRinkens** [comment]
Dat is bekend idd. ik zal vanavond nog eens testen als ik thuis ben. evt met vast image ipv ophalen van camera. thanks.

**Comment by FrankRinkens** [comment]
ik heb de flow opnieuw aangemaakt en het werkt nu weer.

De Dahua cam is niet aan de praat te krijgen die werkt met een secure login form oid. Ik kan wel een screenshot krijgen vanuit mijn mac met ffmpeg commando en dan 1 frame nemen van rtsp stream. Is dit iets dat igrabber ook zou kunnen supporten (toekomst?).

bedankt voor je hulp

**Comment by jordenc** [comment]
Mogelijk zou het compileren van ffmpeg voor de OS versie van Homey wel kunnen, maar denk dat dat voor mij iets te ingewikkeld is (zoveel verstand heb ik daar helaas niet van, maar ik weet dat ze het met Homekit ook op die manier voor elkaar gekregen hebben).

Die secure login is echter iets dat met trial & error wel zou moeten lukken, daar moet ik me binnenkort nog eens op gaan richten.

**Comment by FrankRinkens** [comment]
Ok begrijp ik, je zou usernaame en wachtwoord moeten opslaan en dan login popup misschien moeten afvangen. Maar hier heb ik geen verstand van ;) zou mooi zijn als je dat voor elkaar zou krijgen en ook de dahua cam snapshot werkt.

**Comment by jordenc** [comment]
Het vreemde is, ik heb net een testcase opgezet met een browser wachtwoord popup.

Als ik https://[username]:[password]@www.domein.nl/admin/test.jpg grab werkt het hier probleemloos. Heb je dat al eens op die manier geprobeerd? Als dat niet werkt, maakt
die Dahua mogelijk gebruik van een ander soort protocol om het wachtwoord te verkrijgen... 

Ik weet niet hoeveel werk het voor je is en of je dat sowieso technisch gezien voor elkaar krijgt, maar het zou heel erg helpen als je die camera van buitenaf benaderbaar zou kunnen maken voor me, en dan de URL (inclusief username + password) naar me zou kunnen mailen op info@chamidmedia.nl. Dan kan ik hier even uitgebreider testen ermee.

Mik 'm voor de zekerheid even naar het plafond of doe er een tas omheen o.i.d. tot je 'm weer "niet van buitenaf" bereikbaar maakt.

**Comment by FrankRinkens** [comment]
Yep heb ik getest op die manier werkt het prima voor Foscam maar niet voor Dahua. Ik zal kijken of ik het technisch voor elkaar krijg en dan mail ik je inclusief de juiste link.

**Comment by FrankRinkens** [comment]
Ik krijg het (nu) niet voor elkaar. Misschien in weekend meer succes. Overigens gebruikt de Dahua Cam de Digest Authenticatie en niet Basic Authenticatie, zie ook deze link: https://forum.fibaro.com/topic/26364-problem-ip-camera-dahua-ipc-hdbw4431f-as/ 

Zoals je kunt zien lukt het met HC ook niet, dan zou het wel stoer zijn als voor Homey wel werkend te krijgen is ;)

**Comment by jordenc** [comment]
Goed gevonden; ik denk dat je gelijk hebt, die Digest auth is het probleem. Dat kan ik in de door mij gebruikte software eenvoudig oplossen door een 'sendImmediately': false mee te geven, maar moet even testen hoe dat precies moet. Denk dat ik het binnen een half uur aan de praat krijg zodra ik een testcase heb, dus als het toch nog lukt met die Dahua toegankelijk maken...

**Comment by FrankRinkens** [comment]
Ik heb je info gestuurd om in te loggen.

**Comment by jordenc** [comment]
Version 1.0.1 will feature a new "Grab password protected image" card, where you can select "Don't login immediately" which will work for this webcam.

**Comment by jordenc** [comment]
New version is live in the appstore!
