### ISSUE TITLE
App keeps crashing

### ISSUE THREAD

**Issue by sossienl** [jordenc/image.grabber#2]
I don't know why, but the app keeps crashing. Sometimes after 1 minute, sometimes after several hours. 

I'm running 1.3.2
<img width="514" alt="screen shot 2017-07-02 at 06 44 13" src="https://user-images.githubusercontent.com/609650/27770343-e7718218-5ef1-11e7-88ea-4d6d4294a372.png">

**Comment by jordenc** [comment]
That's strange. Do you have any flows that automaticly run?

I don't think I've seen any notices from Athom, what normally happens. If you put your mouse on the ! mark, does it say anything after a few seconds?

**Comment by jordenc** [comment]
No reaction after 6 months so I'll close it. Feel free to reopen if you still have problems with the latest version.
