### ISSUE TITLE
App Much Slower than previous versions

### ISSUE THREAD

**Issue by Veldkornet** [jordenc/image.grabber#4]
App Version: 0.1.0

Is the new version perhaps slower than it was previously? Or is it just me?

Usually, when someone rang the doorbell, I got the image almost instantly. Now I get it up to 10 seconds later once there is no one at the door anymore. I have the impression that there is now a bit of a delay between Image Grabber’s “Grab Image” and “When an Image is grabbed” since test messages with Telegram seem to be instant.

**Comment by jordenc** [comment]
The "grabbing" code is exactly identical. We now just use the "Athom" way of storing the images. That might be a bit slower. Nothing I can do about that though.

**Comment by Veldkornet** [comment]
@jordenc So, I just wanted to jump back in here and ask, are you sure it's Homey that's causing the delay?

I did the following tests and I added some logs to the flow:

![image](https://user-images.githubusercontent.com/10297361/37289617-6b797680-260a-11e8-9ae0-6cf5a7ba4c51.png)
![image](https://user-images.githubusercontent.com/10297361/37289705-9e0210f8-260a-11e8-850a-c2e0dfebfd66.png)

So, assuming that these logs work how I expect them to, the flows are all done instantly. so... I give up....

Here are my logs from the above (note that it took a minute for me to get the image, where it used to be instant):

2018-03-12 15:27:08 Image Grab Flow Started
2018-03-12 15:27:08 Image Grabbed
2018-03-12 15:27:08 Send Image Flow Started.
2018-03-12 15:27:08 Image Sent

**Comment by Veldkornet** [comment]
Okay, so it seems as though it is the actual grabbing which is slow. Appears to be. In fact, it just spins indefinitely.

On my test flow to grab an image form my IP cam, the little green circle just spins and spins for about a minute, which is in line with the speed I experience.

**Comment by Veldkornet** [comment]
@jordenc can we re-open this issue? Are you sure it's not an ImageGrabber problem?

While it's grabbing the image, my Homey seems to hang as well.
Best seen from the Beta homey app, where if you try to navigate somewhere else, it says "Reconnecting...."
