### ISSUE TITLE
No tags in 1.5.6-rc.11

### ISSUE THREAD

**Issue by tillhenks** [jordenc/image.grabber#6]
Hi,

Just trying the app for the first time. Installs fine but there are no tags in the list of tags.

When I put image grabber as a trigger there are tags on the card and I can drag that tag to eg. email app card. When I check the list of tags however there are no tags from image grabber actually image grabber is not listed at all in tags drop down list. Needless to say the flow does not work...

I've reinstalled the app and restarted Homey no change.

Homey version 1.5.6-rc.11.

**Comment by jordenc** [comment]
It should be there already, I am using it very often.

Please note that the imagegrabber now has a different type of tags with the images than before. The email-sender app also requires this new type of tags now.

If it still doesn't work, feel free to reopen this ticket with some images of what you are trying to accomplish.

**Comment by tillhenks** [comment]
Hi Jorden!
Now it is available and working fine on v0.1.0 on Homey v1.5.7.
Thank you for the app, appreciate that and your work a lot!
