### ISSUE TITLE
Kan het Image token niet gebruiken

### ISSUE THREAD

**Issue by wvwijk** [jordenc/image.grabber#9]
Als ik een flow maak met "Afbeelding is opgehaald" kan ik bij het Telegram "Stuur een afbeelding" veld de Image tag niet plakken. Wat doe ik fout.

Ik heb een flow die een jpg ophaald. Als ik de url tag gebruikt krijg ik netjes een telegram bericht met de url erin.
![send picture flow](https://user-images.githubusercontent.com/34060405/39517312-c8498b80-4dff-11e8-8d1b-dcc977a6dd8f.jpg)

**Comment by jordenc** [comment]
Zo te zien gebruik je een heel flowcard versie van de Telegram app. Ik denk dat je die even opnieuw in moet stellen, dan werkt het wel.
